services:
  api:
    build:
      context: ./api
    command: sh -c "make run"
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      - db
    networks:
      - dashy_network

  migrate:
    profiles: ["migrate"]
    build:
      context: ./api
    entrypoint: ["/entrypoint.migrate.sh"]
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      - db
    networks:
      - dashy_network

  ui:
    build:
      context: ./ui
      target: dev
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - dashy_network

  db:
    image: timescale/timescaledb:latest-pg17
    command: postgres -c shared_preload_libraries=timescaledb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ./api/.env.dev
    networks:
      - dashy_network

volumes:
  postgres_data:

networks:
  dashy_network:
    driver: bridge
