services:
  api:
    build:
      context: ./api
    command: ["uv", "run", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      - db
      - redis
    networks:
      - dashy_network

  worker:
    build:
      context: ./api
    command: ["uv", "run", "celery", "-A", "app", "worker", "-l", "info"]
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      - db
      - redis
    networks:
      - dashy_network

  migrate:
    profiles: ["migrate"]
    build:
      context: ./api
    entrypoint: ["/entrypoint.migrate.sh"]
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      - db
    networks:
      - dashy_network

  ui:
    build:
      context: ./ui
      target: dev
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CI=true
    depends_on:
      - api
    networks:
      - dashy_network

  db:
    image: timescale/timescaledb:latest-pg17
    command: postgres -c shared_preload_libraries=timescaledb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ./api/.env.dev
    networks:
      - dashy_network

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dashy_network

volumes:
  postgres_data:
  redis_data:

networks:
  dashy_network:
    driver: bridge
